### ISSUE TITLE
[1.10.2] Server crash generating world

### ISSUE THREAD

**Issue by Morpheus1101** [maruohon/orecontrol#1]
Crash log @ https://puu.sh/unvtJ/ff234aef03.txt

**Comment by Morpheus1101** [comment]
Ok, so the issue is that i updated the mod and it updated it to a 1.11.2 version when there isnt any further 1.10.2

**Comment by maruohon** [comment]
No, the latest version (0.4.1 atm) should also work in, and is marked for 1.10.2 as well as 1.11.2.
I have a hard time seeing how it could have NPE'd where the log indicates it did...

* Are you using per-dimension configs for Ore Control, or just the regular "master" config?
* And was this was on a dedicated server, right?
* Anything else in the server log from ore control, during the server startup phase?

**Comment by maruohon** [comment]
OH wait now I see it! Fix incoming...

**Comment by Morpheus1101** [comment]
Excellent :)
